import 'dart:io';

import 'package:cff/cff.dart';
import 'package:path/path.dart' as p;

/// Where the pub.dev Example tab reads from.
final examplePath = p.join('example', 'example.md');

/// Builds `example/example.md` from real `cff` output, so the example always
/// shows what the templates generate today.
Future<String> buildExample() async {
  final cubit = await _generate('cubit');
  final bloc = await _generate('bloc');

  return '''
# cff example

Generate a feature named `owl` with a Cubit or a BLoC:

```
dart run cff owl --state cubit
dart run cff owl --state bloc
```

Both variants generate the same `data` and `domain` layers (see the
[generated tree](https://pub.dev/packages/cff#generated-tree)). They differ in
`presentation/bloc/`, the page and `owl_dependencies.dart`.

The files below are generated by `cff` for a project named `my_app`.

## Cubit: `presentation/bloc/owl_cubit.dart`

```dart
${cubit['owl_cubit.dart']}```

## BLoC: `presentation/bloc/owl_bloc.dart`

```dart
${bloc['owl_bloc.dart']}```

## BLoC: `presentation/bloc/owl_event.dart`

```dart
${bloc['owl_event.dart']}```

## Shared by both: `presentation/bloc/owl_state.dart`

```dart
${cubit['owl_state.dart']}```
''';
}

/// Runs `cff owl` in a temporary project; returns the files of
/// `presentation/bloc/` by name.
Future<Map<String, String>> _generate(String state) async {
  final project = Directory.systemTemp.createTempSync('cff_example_');
  try {
    File(p.join(project.path, 'pubspec.yaml')).writeAsStringSync('''
name: my_app
dependencies:
  flutter:
    sdk: flutter
''');

    final err = StringBuffer();
    final code = await CffRunner(
      out: StringBuffer(),
      err: err,
    ).run(['owl', '--state', state], workingDir: project);
    if (code != 0) throw StateError('cff failed for $state: $err');

    final blocDir = Directory(
      p.join(project.path, 'lib', 'feature', 'owl', 'presentation', 'bloc'),
    );
    return {
      for (final file in blocDir.listSync().whereType<File>())
        p.basename(file.path): file.readAsStringSync(),
    };
  } finally {
    project.deleteSync(recursive: true);
  }
}
